version: "3.9"
services:
  mysql:
    image: mysql:8.3.0
    container_name: mysql-expense-tracker
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: expensetrackerdb
      MYSQL_USER: expensetrackeruser
      MYSQL_PASSWORD: expensetrackerpassword
    ports:
      - "3306:3306"
    networks:
      - expense-tracker-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  springboot-expense-tracker-api:
    build:
      context: .
      dockerfile: ./backend/expense-tracker-api/Dockerfile
    container_name: springboot-expense-tracker-api
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/expensetrackerdb
      SPRING_DATASOURCE_USERNAME: expensetrackeruser
      SPRING_DATASOURCE_PASSWORD: expensetrackerpassword
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - expense-tracker-network

networks:
  expense-tracker-network:
    driver: bridge
